In [3]:
from google.colab import drive
drive.mount('/drive')

#import libs
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', None)
import seaborn as sns

plt.rcParams["figure.figsize"] = (28,9)
plt.rcParams["axes.edgecolor"] = "black"
plt.rcParams["axes.linewidth"] = 2.50

#reading the dataset
file = '/drive/MyDrive/globalterrorismdb_0718dist.csv'
data = pd.read_csv(file, encoding='ISO-8859-1')

Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
pd.set_option('max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
data.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,location,summary,crit1,crit2,crit3,doubtterr,alternative,alternative_txt,multiple,success,suicide,attacktype1,attacktype1_txt,attacktype2,attacktype2_txt,attacktype3,attacktype3_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,corp1,target1,natlty1,natlty1_txt,targtype2,targtype2_txt,targsubtype2,targsubtype2_txt,corp2,target2,natlty2,natlty2_txt,targtype3,targtype3_txt,targsubtype3,targsubtype3_txt,corp3,target3,natlty3,natlty3_txt,gname,gsubname,gname2,gsubname2,gname3,gsubname3,motive,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claimmode_txt,claim2,claimmode2,claimmode2_txt,claim3,claimmode3,claimmode3_txt,compclaim,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,weaptype2,weaptype2_txt,weapsubtype2,weapsubtype2_txt,weaptype3,weaptype3_txt,weapsubtype3,weapsubtype3_txt,weaptype4,weaptype4_txt,weapsubtype4,weapsubtype4_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propextent_txt,propvalue,propcomment,ishostkid,nhostkid,nhostkidus,nhours,ndays,divert,kidhijcountry,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,ransomnote,hostkidoutcome,hostkidoutcome_txt,nreleased,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,Central America & Caribbean,NaN,Santo Domingo,18.456792,-69.951164,1.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,1,Assassination,NaN,NaN,NaN,NaN,14,Private Citizens & Property,68.0,Named Civilian,NaN,Julio Guzman,58.0,Dominican Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANO-D,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,North America,Federal,Mexico city,19.371887,-99.086624,1.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,6,Hostage Taking (Kidnapping),NaN,NaN,NaN,NaN,7,Government (Diplomatic),45.0,"Diplomatic Personnel (outside of embassy, cons...",Belgian Ambassador Daughter,"Nadine Chaval, daughter",21.0,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23rd of September Communist League,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,NaN,Mexico,1.0,800000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,4.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,1,Assassination,NaN,NaN,NaN,NaN,10,Journalists & Media,54.0,Radio Journalist/Staff/Facility,Voice of America,Employee,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,Western Europe,Attica,Athens,37.997490,23.762728,1.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,7,Government (Diplomatic),46.0,Embassy/Consulate,NaN,U.S. Embassy,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,16.0,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Explosive,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,East Asia,Fukouka,Fukouka,33.580412,130.396361,1.0,0,NaN,NaN,1,1,1,-9.0,NaN,NaN,0.0,1,0,7,Facility/Infrastructure Attack,NaN,NaN,NaN,NaN,7,Government (Diplomatic),46.0,Embassy/Consulate,NaN,U.S. Consulate,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [15]:
data.rename(columns={'iyear':'Year','extended':'Incident_Duration','city':'City','country_txt':'Country','region_txt':'Region','summary':'Summary', 'success':'Success',
                     'alternative_txt':'Attack_Tactic','attacktype1_txt':'Attack_type','suicide':'Suicide','targtype1_txt':'Target_type','targsubtype1_txt':'Target_SubCat',
                     'gname':'Terror_Group','motive':'Terror_Motive','weaptype1_txt':'Weapon_Type','weapsubtype1_txt':'Weapon_Subtype','nkill':'Total_Killed',
                     'nwoundus':'Total_Wounded','nkillter':'Terrorists_Killed','propextent_txt':'Prorperty_Damage','ishostkid':'Hostage_con',
                     'ransom':'Ransom','ransomamt':'Ransom_amt','ransompaid':'Ransom_amt_paid','hostkidoutcome_txt':'Hostage_outcome'}, inplace=True)

In [17]:
finData = data[['Year', 'Incident_Duration', 'City', 'Country', 'Region', 'Summery', 'Success','Attack_Tactic','Attack_type',
                'Suicide','Target_type','Target_SubCat','Terror_Group','Terror_Motive','Weapon_Type','Weapon_Subtype','Total_Killed','Total_Wounded',
                'Terrorists_Killed','Prorperty_Damage','Hostage_con','Ransom','Ransom_amt','Ransom_amt_paid','Hostage_outcome']].reset_index(drop=True)

In [14]:
finData.head()

,Year,Incident_Duration,City,Country,Region,Summery,Success,Attack_Tactic,Attack_type,Suicide,Target_type,Target_SubCat,Terror_Group,Terror_Motive,Weapon_Type,Weapon_Subtype,Total_Killed,Total_Wounded,Terrorists_Killed,Prorperty_Damage,Hostage_con,Ransom,Ransom_amt,Ransom_amt_paid,Hostage_outcome
0,1970,0,Santo Domingo,Dominican Republic,Central America & Caribbean,NaN,1,NaN,Assassination,0,Private Citizens & Property,Named Civilian,MANO-D,NaN,Unknown,NaN,1.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
1,1970,0,Mexico city,Mexico,North America,NaN,1,NaN,Hostage Taking (Kidnapping),0,Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",23rd of September Communist League,NaN,Unknown,NaN,0.0,NaN,NaN,NaN,1.0,1.0,800000.0,NaN,NaN
2,1970,0,Unknown,Philippines,Southeast Asia,NaN,1,NaN,Assassination,0,Journalists & Media,Radio Journalist/Staff/Facility,Unknown,NaN,Unknown,NaN,1.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
3,1970,0,Athens,Greece,Western Europe,NaN,1,NaN,Bombing/Explosion,0,Government (Diplomatic),Embassy/Consulate,Unknown,NaN,Explosives,Unknown Explosive Type,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
4,1970,0,Fukouka,Japan,East Asia,NaN,1,NaN,Facility/Infrastructure Attack,0,Government (Diplomatic),Embassy/Consulate,Unknown,NaN,Incendiary,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN

In [22]:
finData.isnull().sum()

Year                      0
Incident_Duration         0
City                    434
Country                   0
Region                    0
Summery               66129
Success                   0
Attack_Tactic        152680
Attack_type               0
Suicide                   0
Target_type               0
Target_SubCat         10373
Terror_Group              0
Terror_Motive        131130
Weapon_Type               0
Weapon_Subtype        20768
Total_Killed          10313
Total_Wounded         64702
Terrorists_Killed     66958
Prorperty_Damage     117626
Hostage_con             178
Ransom               104310
Ransom_amt           180341
Ransom_amt_paid      180917
Hostage_outcome      170700
dtype: int64

In [23]:
# City Column
finData['City'].fillna('Unknown', inplace = True)

# Summery Column 
finData['Summery'].fillna('Unknown', inplace = True)

# Terror_Motive column
finData['Terror_Motive'].fillna('Unknown', inplace = True)

# Prorperty_Damage column
finData['Prorperty_Damage'].fillna('Unknown', inplace = True)

# Attack_Tactic column
finData['Attack_Tactic'].fillna('Unknown', inplace = True)

# Target_SubCat column
finData['Target_SubCat'].fillna('Unknown', inplace = True)

# Weapon_Subtype column
finData['Weapon_Subtype'].fillna('Unknown', inplace = True)

# Filling null values in Hostage_outcome column
finData['Hostage_outcome'].fillna('Unknown', inplace = True)

# Summery column
finData['Summery'].fillna('Undocumented', inplace = True)

# Filling null values in Ransom_amt_paid column
finData['Ransom_amt_paid'].fillna(0, inplace = True)

# Filling null values in Ransom_amt column
finData['Ransom_amt'].fillna(0, inplace = True)

# Filling null values in Ransom_amt column
finData['Ransom'].fillna(-9.0, inplace = True)

# Replacing floating values with for better meaningful categorial value
finData[['Hostage_con','Ransom']] = finData[['Hostage_con','Ransom']].replace({0.0:'NO', 1.0:'Yes', -9.0:'Unknown'})

In [25]:
# Total_Killed Column
finData['Total_Killed'] = finData['Total_Killed'].fillna(finData['Total_Killed'].mode()[0])

# Total_Wounded Column
finData['Total_Wounded'] = finData['Total_Wounded'].fillna(finData['Total_Wounded'].mode()[0])

# Terrorists_Killed Column
finData['Terrorists_Killed'] = finData['Terrorists_Killed'].fillna(finData['Terrorists_Killed'].mode()[0])

# Creating a new Column to show total_Casualities which is just a total number of people who got wounded and 
# killed in that incident including all Attackers, Defenders and Civilians

finData['Total_Casualities'] = finData['Total_Killed'] + finData['Total_Wounded']

In [28]:
finData.head()

,Year,Incident_Duration,City,Country,Region,Summery,Success,Attack_Tactic,Attack_type,Suicide,Target_type,Target_SubCat,Terror_Group,Terror_Motive,Weapon_Type,Weapon_Subtype,Total_Killed,Total_Wounded,Terrorists_Killed,Prorperty_Damage,Hostage_con,Ransom,Ransom_amt,Ransom_amt_paid,Hostage_outcome,Total_Casualities
0,1970,0,Santo Domingo,Dominican Republic,Central America & Caribbean,Unknown,1,Unknown,Assassination,0,Private Citizens & Property,Named Civilian,MANO-D,Unknown,Unknown,Unknown,1.0,0.0,0.0,Unknown,NO,NO,0.0,0.0,Unknown,1.0
1,1970,0,Mexico city,Mexico,North America,Unknown,1,Unknown,Hostage Taking (Kidnapping),0,Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",23rd of September Communist League,Unknown,Unknown,Unknown,0.0,0.0,0.0,Unknown,Yes,Yes,800000.0,0.0,Unknown,0.0
2,1970,0,Unknown,Philippines,Southeast Asia,Unknown,1,Unknown,Assassination,0,Journalists & Media,Radio Journalist/Staff/Facility,Unknown,Unknown,Unknown,Unknown,1.0,0.0,0.0,Unknown,NO,NO,0.0,0.0,Unknown,1.0
3,1970,0,Athens,Greece,Western Europe,Unknown,1,Unknown,Bombing/Explosion,0,Government (Diplomatic),Embassy/Consulate,Unknown,Unknown,Explosives,Unknown Explosive Type,0.0,0.0,0.0,Unknown,NO,NO,0.0,0.0,Unknown,0.0
4,1970,0,Fukouka,Japan,East Asia,Unknown,1,Unknown,Facility/Infrastructure Attack,0,Government (Diplomatic),Embassy/Consulate,Unknown,Unknown,Incendiary,Unknown,0.0,0.0,0.0,Unknown,NO,NO,0.0,0.0,Unknown,0.0